In [ ]:
from google.colab import drive
drive.mount('/content/drive')
path="/content/drive/My Drive/Courses/Advanced topic/project/Dataset/"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from random import random
from math import exp
from random import seed
import gzip
import csv
import pandas as pd
import numpy as np
import re
import glob
from collections import defaultdict
from sklearn.preprocessing import MinMaxScaler,StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score

In [ ]:
path='/content/drive/My Drive/Courses/Advanced topic/project/Dataset/'
df=pd.read_csv(path+"Methylation/Final DNA Methylation with Sample.csv",index_col=-1).sort_index()

In [ ]:
df=df.reindex(sorted(df.columns), axis=1)
df

A1BG  AASDH   AASS  ABCA11P  ABCA6  ABCA9  ABCB11  ABCC6P1  \
sample                                                                       
CRC01_LN1_162  0.510  0.570  0.506    0.703  0.893  0.581   0.693    0.388   
CRC01_LN1_164  0.550  0.620  0.562    0.704  0.835  0.555   0.726    0.370   
CRC01_LN1_166  0.585  0.629  0.642    0.641  0.832  0.633   0.727    0.482   
CRC01_LN1_167  0.594  0.619  0.628    0.656  0.868  0.630   0.710    0.483   
CRC01_LN1_168  0.460  0.458  0.531    0.463  0.650  0.505   0.565    0.502   
...              ...    ...    ...      ...    ...    ...     ...      ...   
CRC11_PT4_741  0.535  0.519  0.599    0.565  0.777  0.569   0.636    0.513   
CRC11_PT4_742  0.571  0.568  0.632    0.594  0.851  0.636   0.671    0.563   
CRC11_PT4_746  0.545  0.515  0.597    0.591  0.822  0.569   0.651    0.446   
CRC11_PT4_747  0.541  0.484  0.602    0.536  0.789  0.567   0.650    0.486   
CRC11_PT4_748  0.560  0.488  0.614    0.553  0.809  0.581   0.636    0.549   

               ABCG1  ABHD13  ...   RPA3  RPAP1   RPGR  RPL10  RPL10L  \
sample                        ...                                       
CRC01_LN1_162  0.488   0.735  ...  0.746  0.687  0.822  0.619   0.870   
CRC01_LN1_164  0.725   0.776  ...  0.629  0.647  0.717  0.623   0.902   
CRC01_LN1_166  0.560   0.773  ...  0.645  0.640  0.748  0.602   0.852   
CRC01_LN1_167  0.545   0.786  ...  0.650  0.642  0.705  0.647   0.845   
CRC01_LN1_168  0.471   0.612  ...  0.426  0.441  0.548  0.414   0.739   
...              ...     ...  ...    ...    ...    ...    ...     ...   
CRC11_PT4_741  0.514   0.680  ...  0.572  0.505  0.636  0.572   0.553   
CRC11_PT4_742  0.599   0.704  ...  0.629  0.559  0.649  0.604   0.507   
CRC11_PT4_746  0.534   0.677  ...  0.556  0.559  0.618  0.580   0.550   
CRC11_PT4_747  0.534   0.669  ...  0.526  0.531  0.573  0.534   0.501   
CRC11_PT4_748  0.576   0.679  ...  0.572  0.497  0.631  0.554   0.560   

               RPL13AP6  RPL23A   RPL3  RPL30  RPL36  
sample                                                
CRC01_LN1_162     0.562   0.559  0.808  0.767  0.676  
CRC01_LN1_164     0.591   0.578  0.826  0.686  0.690  
CRC01_LN1_166     0.626   0.646  0.825  0.743  0.652  
CRC01_LN1_167     0.622   0.643  0.860  0.705  0.647  
CRC01_LN1_168     0.492   0.485  0.580  0.553  0.561  
...                 ...     ...    ...    ...    ...  
CRC11_PT4_741     0.549   0.571  0.738  0.632  0.622  
CRC11_PT4_742     0.615   0.590  0.735  0.697  0.647  
CRC11_PT4_746     0.543   0.543  0.737  0.586  0.613  
CRC11_PT4_747     0.568   0.555  0.685  0.621  0.561  
CRC11_PT4_748     0.563   0.551  0.761  0.603  0.612  

[609 rows x 1712 columns]

In [ ]:
df_pdi=pd.read_csv(path+'PDI/PDI_weights_new_dm.csv',index_col=0).sort_index()
# df_pdi=pd.read_csv(path+'PPI/PPI_new_dm_weights.csv',index_col=0).sort_index()
df_pdi= df_pdi.sort_values(by=['Unnamed: 0.1'])
index = df_pdi['Unnamed: 0.1']
df_pdi= df_pdi.drop(['Unnamed: 0.1'],axis=1)
df_pdi.index =index
# df_ppi=df_ppi.T
df_pdi

CEBPE  CREM  ESR2  GATA1  HSF2  NR2F2  RELA  RFX1  ATF7  MEIS1  \
Unnamed: 0.1                                                                   
A1BG            0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
AASDH           0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
AASS            0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
ABCA11P         0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
ABCA6           0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
...             ...   ...   ...    ...   ...    ...   ...   ...   ...    ...   
RPL13AP6        0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
RPL23A          0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
RPL3            0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
RPL30           0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
RPL36           0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   

              CTCFL  FOXA2  MEF2A  MAFK  POU5F1  MAFB  
Unnamed: 0.1                                           
A1BG            0.0    0.0    0.0   0.0     0.0   0.0  
AASDH           0.0    0.0    0.0   0.0     0.0   0.0  
AASS            0.0    0.0    0.0   0.0     0.0   0.0  
ABCA11P         0.0    0.0    0.0   0.0     0.0   0.0  
ABCA6           0.0    0.0    0.0   0.0     0.0   0.0  
...             ...    ...    ...   ...     ...   ...  
RPL13AP6        0.0    0.0    0.0   0.0     0.0   0.0  
RPL23A          0.0    0.0    0.0   0.0     0.0   0.0  
RPL3            0.0    0.0    0.0   0.0     0.0   0.0  
RPL30           0.0    0.0    0.0   0.0     0.0   0.0  
RPL36           0.0    0.0    0.0   0.0     0.0   0.0  

[1712 rows x 16 columns]

In [ ]:
extra=False
if(extra):
  for i in range(11):
    df_pdi[str(i)]=0.33
df_pdi


CEBPE  CREM  ESR2  GATA1  HSF2  NR2F2  RELA  RFX1  ATF7  MEIS1  \
Unnamed: 0.1                                                                   
A1BG            0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
AASDH           0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
AASS            0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
ABCA11P         0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
ABCA6           0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
...             ...   ...   ...    ...   ...    ...   ...   ...   ...    ...   
RPL13AP6        0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
RPL23A          0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
RPL3            0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
RPL30           0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   
RPL36           0.0   0.0   0.0    0.0   0.0    0.0   0.0   0.0   0.0    0.0   

              CTCFL  FOXA2  MEF2A  MAFK  POU5F1  MAFB  
Unnamed: 0.1                                           
A1BG            0.0    0.0    0.0   0.0     0.0   0.0  
AASDH           0.0    0.0    0.0   0.0     0.0   0.0  
AASS            0.0    0.0    0.0   0.0     0.0   0.0  
ABCA11P         0.0    0.0    0.0   0.0     0.0   0.0  
ABCA6           0.0    0.0    0.0   0.0     0.0   0.0  
...             ...    ...    ...   ...     ...   ...  
RPL13AP6        0.0    0.0    0.0   0.0     0.0   0.0  
RPL23A          0.0    0.0    0.0   0.0     0.0   0.0  
RPL3            0.0    0.0    0.0   0.0     0.0   0.0  
RPL30           0.0    0.0    0.0   0.0     0.0   0.0  
RPL36           0.0    0.0    0.0   0.0     0.0   0.0  

[1712 rows x 16 columns]

In [ ]:
if(np.all(df_pdi.index== df.columns[:])):
  print("same")
weights_pdi=[]
for i,cols in enumerate(df_pdi.columns):
  if(i!=0):
    weights_pdi.append(df_pdi[cols].values)
    
weights_pdi=np.array(weights_pdi)
weights_pdi.shape

same


(15, 1712)

In [ ]:
weights_pdi

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:

# from keras.wrappers.scikit_learn import KerasClassifier
# from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import explained_variance_score
import tensorflow as tf
from tensorflow import keras 
from keras.models import Sequential, Model, Input
from keras.layers import Dense, Dropout
from sklearn import preprocessing
from tensorflow.keras.optimizers import SGD
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score

In [ ]:
regions=[]
for j,i in enumerate(df.iterrows()):
  cat=i[0]
  m=re.search("_", cat)
  cat=cat[m.end():len(cat)]
  m=re.search("_", cat)
  cat=cat[m.start()-3:m.start()-1]
  regions.append(cat)
df['regions']=regions

In [ ]:
le = preprocessing.LabelEncoder()
scaler = StandardScaler()
le.fit(df['regions'])
data=df.drop(['regions'],axis=1)
# data=df_trans.
data=data.iloc[:,:]
data=(np.array(data).astype(np.float32))
scaler.fit(data)
data=scaler.transform(data)
y=le.transform(df['regions'])

In [ ]:
import keras.backend as K
class CustomConnected(Dense):

    def __init__(self,units,connections,**kwargs):

        #this is matrix A
        # self.set_weights= connections
        self.connections = connections                        

        #initalize the original Dense with all the usual arguments   
        super(CustomConnected,self).__init__(units,**kwargs)  


    def call(self, inputs):
      output = K.dot(inputs, self.kernel * self.connections)
      if self.use_bias:
          output = K.bias_add(output, self.bias)
      if self.activation is not None:
          output = self.activation(output)
      return output

In [ ]:
tf.convert_to_tensor(weights_pdi.T)

<tf.Tensor: shape=(1712, 15), dtype=float64, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])>

In [ ]:
def create_model_tuning(layer_one=50,  layer_two=10,  activation_fuction_one='relu',activation_fuction_two='relu',drop_out_p=0.4, learningrate=0.1):
  model = tf.keras.models.Sequential()
  model.add(tf.keras.Input(shape=(data.shape[1],)))
  # model.add(tf.keras.layers.Dense(layer_two, activation='relu'))
  model.add(CustomConnected(weights_pdi.shape[0],tf.convert_to_tensor(weights_pdi.T, dtype=tf.float32), activation=activation_fuction_one))
  # model.add(tf.keras.layers.Dense(layer_one,kernel_initializer='lecun_uniform', activation=activation_fuction_two))
  model.add(Dropout(drop_out_p))
  model.add(tf.keras.layers.Dense(layer_one,kernel_initializer='lecun_uniform', activation=activation_fuction_two))
  
  model.add(tf.keras.layers.Dense(layer_two, activation='relu'))
  model.add(tf.keras.layers.Dense(4, activation='sigmoid'))
  model.layers[0].set_weights([weights_pdi.T, np.zeros(model.layers[0].get_weights()[1].shape)])
  optimizer = SGD(learning_rate=learningrate, momentum=0.03)
  model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy',metrics= 'accuracy')
  
  return model

In [ ]:
RANDOME_STATE=2000
def tune_hyperparameter(X,y):
  reports=[]
  test_score=[]
  train_score=[]
  best_score=-1
  cf=[]
  best_model=  create_model_tuning(1,1,'relu','relu',0.4,0.1)
  Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=RANDOME_STATE,stratify=y)
  layer_one=[ 10,20, 50, 100]
  layer_two= [4, 8, 10]
  activation_fuction_one = ['linear','relu','sigmoid']
  activation_fuction_two = ['relu','sigmoid']
  drop_out_p = [0.1,0.2]
  learningrate = [0.1]
  lo,lt,afo,aft,dop,lrt = [],[],[],[],[],[]
  acc_test, f1_test= [],[]
  acc_train,f1_train = [],[]
  for l1 in layer_one:
    for l2 in layer_two:
      for af1 in activation_fuction_one:
        for af2 in activation_fuction_two:
          for d in drop_out_p:
            for l in learningrate:
              model=create_model_tuning(l1,l2,af1,af2, d, l)
              lo.append(l1)
              lt.append(l2)
              afo.append(af1)
              print(af2)
              aft.append(af2)
              dop.append(d)
              lrt.append(l)    
              model.fit(Xtrain,ytrain,validation_data=(Xtest,ytest), epochs=50)
              y_pred=model.predict(Xtest)
              max_value = np.argmax(y_pred, axis=1)
              y_pred_train=model.predict(Xtrain)
              max_value_train = np.argmax(y_pred_train, axis=1)
              if(best_score<f1_score(ytest, max_value, average='macro')):
                best_score=f1_score(ytest, max_value, average='macro')
                best_model=model
              f1_test.append(f1_score(ytest, max_value, average='macro'))
              f1_train.append(f1_score(ytrain, max_value_train, average='macro'))
              acc_test.append(accuracy_score(ytest, max_value))
              acc_train.append(accuracy_score(ytrain, max_value_train))
              tuning_result= pd.DataFrame(list(zip(lo,lt,afo,aft,dop,lrt,f1_test,f1_train,acc_test,acc_train)),columns =['layer_one','layer_two','activation_one','activation_two','dropout','learning_rate','f1_val','f1_train','acc_val','acc_tests'])
              tuning_result.to_csv("/content/drive/My Drive/Courses/Advanced topic/project/Hyper-parameter tuning/hyperparameter_tuning_with_new_DM_pdi_common_samples_one_layer_v2.csv")
  tuning_result= pd.DataFrame(list(zip(lo,lt,afo,aft,dop,lrt,f1_test,f1_train,acc_test,acc_train)),columns =['layer_one','layer_two','activation_one','activation_two','dropout','learning_rate','f1_val','f1_train','acc_val','acc_tests'])
  tuning_result.to_csv("/content/drive/My Drive/Courses/Advanced topic/project/Hyper-parameter tuning/hyperparameter_tuning_with_new_DM_ppi_common_samples_one_layer_v2.csv")
  print(tuning_result)
 
  return best_model,tuning_result

In [ ]:
tuning = False
if(tuning):
  X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.5, random_state=RANDOME_STATE,stratify=y)
  best_model, results=tune_hyperparameter(X_train,y_train)
  y_pred = best_model.predict(X_test)
  max_value = np.argmax(y_pred, axis=1)
  f1_score(y_test, max_value, average='macro')
  best_model.summary()
  results.to_csv("/content/drive/My Drive/Courses/Advanced topic/project/Hyper-parameter tuning/hyperparameter_tuning_with_new_DE_ppi_common_sample_v2.csv")

In [ ]:
def create_model():
  model = tf.keras.models.Sequential()
  model.add(tf.keras.Input(shape=(data.shape[1],)))
  model.add(CustomConnected(weights_pdi.shape[0],tf.convert_to_tensor(weights_pdi.T, dtype=tf.float32)))
  model.add(tf.keras.layers.Dense(50,kernel_initializer='lecun_uniform', activation='linear'))
  model.add(Dropout(0.1))
  model.add(tf.keras.layers.Dense(10, activation='relu'))
  model.add(tf.keras.layers.Dense(4, activation='softmax'))
  optimizer = SGD(learning_rate=0.01, momentum=0.03)
  model.layers[0].set_weights([weights_pdi.T, np.zeros(model.layers[0].get_weights()[1].shape)])
  model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy',metrics= 'accuracy')
  return model

In [ ]:
def stratfiedk_fold_cross_validation(X,y,n,r):
  skf = StratifiedKFold(n_splits=n, shuffle=True, random_state=r)
  best_score=-1
  best_model=create_model()
  for train, test in skf.split(X,y):
    Xtrain, X_val =X[train], X[test]
    ytrain, y_val =y[train], y[test]
    model=create_model()
    print("Before")
    print(model.layers[0].get_weights()[0][0])
    print(model.layers[0].get_weights()[0][12])
    model.fit(tf.convert_to_tensor(Xtrain),tf.convert_to_tensor(ytrain),validation_data=(tf.convert_to_tensor(X_val),tf.convert_to_tensor(y_val)),epochs=50)
    print(model.layers[0].get_weights()[0][0])
    print(model.layers[0].get_weights()[0][12])
    y_pred=model.predict(X_val)
    max_value = np.argmax(y_pred, axis=1)    
    if(best_score<f1_score(y_val, max_value, average='macro')):
      best_score=f1_score(y_val, max_value, average='macro')
      best_model=model
  
  return best_model

In [ ]:
y=le.transform(df['regions'])
RANDOME_STATES =[1000]
# X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.2, random_state=RANDOME_STATE,stratify=y)
# train_acc,test_acc,reports,best_model,confusion_matrixes=stratfiedk_fold_cross_validation(X_train,y_train,5)
f1_folds_scores=[]
for r in RANDOME_STATES:
  skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=r)
  for train, test in skf.split(data,y):
    X_train, X_test =data[train], data[test]
    y_train, y_test =y[train], y[test]
    best_model=stratfiedk_fold_cross_validation(X_train,y_train,5,r)
    y_pred=best_model.predict(X_test)
    max_value = np.argmax(y_pred, axis=1)
    f1_folds_scores.append(classification_report(y_test, max_value, output_dict=True ))

Before
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
Epoch 1/50
13/13 [==============================] - 1s 28ms/step - loss: 2.1163 - accuracy: 0.3728 - val_loss: 1.8578 - val_accuracy: 0.3673
Epoch 2/50
13/13 [==============================] - 0s 7ms/step - loss: 1.6441 - accuracy: 0.4370 - val_loss: 2.2368 - val_accuracy: 0.3673
Epoch 3/50
13/13 [==============================] - 0s 7ms/step - loss: 1.5721 - accuracy: 0.4242 - val_loss: 1.8349 - val_accuracy: 0.3878
Epoch 4/50
13/13 [==============================] - 0s 11ms/step - loss: 1.3270 - accuracy: 0.4781 - val_loss: 1.8756 - val_accuracy: 0.4592
Epoch 5/50
13/13 [==============================] - 0s 7ms/step - loss: 1.4734 - accuracy: 0.4987 - val_loss: 1.1313 - val_accuracy: 0.4898
Epoch 6/50
13/13 [==============================] - 0s 7ms/step - loss: 1.1222 - accuracy: 0.5090 - val_loss: 1.2216 - val_accuracy: 0.4796
Epoch 7/50
13/13 [==============================] - 0s 9m

In [ ]:
#  f1_folds_scores[0]['0']
classes=['0','1','2','3']
precisions, recalls, f1_scores,supports=[],[],[],[]
accurcies,m_precision,m_recall,m_f1_score,w_precision,w_recall,w_f1_score=[],[],[],[],[],[],[]
for l in range(0,len(f1_folds_scores)):
  print(f1_folds_scores[l])
  for c in classes:
    precisions.append(f1_folds_scores[l][c]['precision'])
    recalls.append(f1_folds_scores[l][c]['recall'])
    f1_scores.append(f1_folds_scores[l][c]['f1-score'])
    supports.append(f1_folds_scores[l][c]['support'])
  accurcies.append(f1_folds_scores[l]['accuracy'])
  m_precision.append(f1_folds_scores[l]['macro avg']['precision'])
  m_recall.append(f1_folds_scores[l]['macro avg']['recall'])
  m_f1_score.append(f1_folds_scores[l]['macro avg']['f1-score'])
  w_precision.append(f1_folds_scores[l]['weighted avg']['precision'])
  w_recall.append(f1_folds_scores[l]['weighted avg']['recall'])
  w_f1_score.append(f1_folds_scores[l]['weighted avg']['f1-score'])

In [ ]:
overall_results= pd.DataFrame(list(zip(accurcies,m_precision,m_recall,m_f1_score,w_precision,w_recall,w_f1_score)),columns =['accuracy','macro_precision','macro_recall','macro_f1','weighted_precision','weighted_recall','weighted_f1_score'])
overall_results.describe()